{
  "id": "computation/1",
  "number": 1,
  "name": "Computation Club 1",
  "date": 1543917600000,
  "entries": [
    {
      "id": "1-a",
      "number": 1,
      "humanNumber": "1",
      "clue": "See 10 across",
      "direction": "across",
      "length": 8,
      "group": ["10-a", "1-a"],
      "position": { "x": 1, "y": 0 },
      "separatorLocations": {},
      "solution": "COMPLETE"
    },
    {
      "id": "2-a",
      "number": 2,
      "humanNumber": "2",
      "clue": "Type (abbr.) (4)",
      "direction": "across",
      "length": 4,
      "group": ["2-a"],
      "position": { "x": 10, "y": 0 },
      "separatorLocations": {},
      "solution": "BOOL"
    },
    {
      "id": "4-a",
      "number": 4,
      "humanNumber": "4",
      "clue": "How we program (6)",
      "direction": "across",
      "length": 3,
      "group": ["4-a"],
      "position": { "x": 1, "y": 2 },
      "separatorLocations": {},
      "solution": "MOB"
    },
    {
      "id": "5-a",
      "number": 5,
      "humanNumber": "5",
      "clue": "See 17 down",
      "direction": "across",
      "length": 7,
      "group": ["18-d", "14-a", "5-a"],
      "position": { "x": 5, "y": 2 },
      "separatorLocations": {},
      "solution": "SCHEMER"
    },
    {
      "id": "7-a",
      "number": 7,
      "humanNumber": "7",
      "clue": "Book (13, 11)",
      "direction": "across",
      "length": 13,
      "group": ["7-a", "1-d"],
      "position": { "x": 1, "y": 4 },
      "separatorLocations": {},
      "solution": "UNDERSTANDING"
    },
    {
      "id": "10-a",
      "number": 10,
      "humanNumber": "10",
      "clue": "(C.) When language is computationally universal it makes computer tingle (6,8)",
      "direction": "across",
      "length": 6,
      "group": ["10-a", "1-a"],
      "position": { "x": 5, "y": 6 },
      "separatorLocations": {},
      "solution": "TURING"
    },
    {
      "id": "13-a",
      "number": 13,
      "humanNumber": "13",
      "clue": "Editor",
      "direction": "across",
      "length": 3,
      "group": ["13-a"],
      "position": { "x": 0, "y": 8 },
      "separatorLocations": {},
      "solution": "VIM"
    },
    {
      "id": "14-a",
      "number": 14,
      "humanNumber": "14",
      "clue": "See 17 down",
      "direction": "across",
      "length": 6,
      "group": ["18-d", "14-a", "5-a"],
      "position": { "x": 4, "y": 9 },
      "separatorLocations": {},
      "solution": "LITTLE"
    },
    {
      "id": "16-a",
      "number": 16,
      "humanNumber": "16",
      "clue": "(Cryptic) First to outsmart doctor becomes author of a book (3,6)",
      "direction": "across",
      "length": 3,
      "group": ["16-a", "8-d"],
      "position": { "x": 12, "y": 9 },
      "separatorLocations": {},
      "solution": "TOM"
    },
    {
      "id": "17-a",
      "number": 17,
      "humanNumber": "17",
      "clue": "Language (6)",
      "direction": "across",
      "length": 6,
      "group": ["17-a"],
      "position": { "x": 3, "y": 12 },
      "separatorLocations": {},
      "solution": "ELIXIR"
    },
    {
      "id": "19-a",
      "number": 19,
      "humanNumber": "19",
      "clue": "S can be safely used in place of T if it is a ... (6)",
      "direction": "across",
      "length": 7,
      "group": ["19-a"],
      "position": { "x": 4, "y": 14 },
      "separatorLocations": {},
      "solution": "SUBTYPE"
    },
    {
      "id": "1-d",
      "number": 1,
      "humanNumber": "1",
      "clue": "See 7 across",
      "direction": "down",
      "length": 11,
      "group": ["7-a", "1-d"],
      "position": { "x": 1, "y": 0 },
      "separatorLocations": {},
      "solution": "COMPUTATION"
    },
    {
      "id": "2-d",
      "number": 2,
      "humanNumber": "2",
      "clue": "Goes well with babaganoush (5)",
      "direction": "down",
      "length": 5,
      "group": ["2-d"],
      "position": { "x": 10, "y": 0 },
      "separatorLocations": {},
      "solution": "BREAD"
    },
    {
      "id": "3-d",
      "number": 3,
      "humanNumber": "3",
      "clue": "Language (3)",
      "direction": "down",
      "length": 3,
      "group": ["3-d"],
      "position": { "x": 13, "y": 0 },
      "separatorLocations": {},
      "solution": "LUA"
    },
    {
      "id": "6-d",
      "number": 6,
      "humanNumber": "6",
      "clue": "A way to share behaviour and properties",
      "direction": "down",
      "length": 11,
      "group": ["6-d"],
      "position": { "x": 12, "y": 3 },
      "separatorLocations": {},
      "solution": "INHERITANCE"
    },
    {
      "id": "8-d",
      "number": 8,
      "humanNumber": "8",
      "clue": "See 15 across",
      "direction": "down",
      "length": 6,
      "group": ["16-a", "8-d"],
      "position": { "x": 6, "y": 4 },
      "separatorLocations": {},
      "solution": "STUART"
    },
    {
      "id": "9-d",
      "number": 9,
      "humanNumber": "9",
      "clue": "(Cryptic) Fernando has a gate (4)",
      "direction": "down",
      "length": 4,
      "group": ["9-d"],
      "position": { "x": 9, "y": 4 },
      "separatorLocations": {},
      "solution": "NAND"
    },
    {
      "id": "11-d",
      "number": 11,
      "humanNumber": "11",
      "clue": "See 12 down",
      "direction": "down",
      "length": 8,
      "group": ["12-d", "11-d"],
      "position": { "x": 4, "y": 7 },
      "separatorLocations": {},
      "solution": "CALCULUS"
    },
    {
      "id": "12-d",
      "number": 12,
      "humanNumber": "12",
      "clue": "e.g. λx.x (6,8)",
      "direction": "down",
      "length": 6,
      "group": ["12-d", "11-d"],
      "position": { "x": 14, "y": 7 },
      "separatorLocations": {},
      "solution": "LAMBDA"
    },
    {
      "id": "15-d",
      "number": 15,
      "humanNumber": "15",
      "clue": "(Cryptic) Everyone likes my beginners language (3)",
      "direction": "down",
      "length": 3,
      "group": ["15-d"],
      "position": { "x": 9, "y": 9 },
      "separatorLocations": {},
      "solution": "ELM"
    },
    {
      "id": "18-d",
      "number": 18,
      "humanNumber": "18",
      "clue": "Book (3,6,7)",
      "direction": "down",
      "length": 3,
      "group": ["18-d", "14-a", "5-a"],
      "position": { "x": 10, "y": 12 },
      "separatorLocations": {},
      "solution": "THE"
    }
  ],
  "solutionAvailable": false,
  "dateSolutionAvailable": 154400400000,
  "dimensions": {
    "cols": 15,
    "rows": 15
  },
  "crosswordType": "cryptic"
}
